# source: recon catalog for 'monarch', operation 'Common_GetMe'
# query_hash: 45b63a9705a457f5a8500e84a13b4e9373a409b5c798b103fbc8f0a51bcf1d50
# observed in run(s): 2026-09-23T15-40-10Z, 2026-09-23T16-27-05Z, 2026-09-24T14-30-04Z
# last_seen: 2026-09-24T14:30:45.925000+00:00
# exported: 2026-09-24T15:53:35.162223+00:00
# NOT authoritative -- catalog is built from OBSERVED traffic, not a schema fetch.

query Common_GetMe {
  me {
    ...UserFields
    id
    profile {
      id
      hasSeenCategoriesManagementTour
      dismissedTransactionsListUpdatesTourAt
      viewedMarkAsReviewedUpdatesCalloutAt
      hasDismissedWhatsNewAt
      collaboratesOnFinancesDetailed
      webUiThemePreference
      mobileUiThemePreference
      __typename
    }
    attributionData {
      runwayerOnboardId
      onboardingQuizCompleted
      __typename
    }
    onboardingTemplate {
      slug
      displayName
      partnerName
      __typename
    }
    __typename
  }
}

fragment UserFields on User {
  birthday
  email
  displayName
  id
  isSuperuser
  name
  timezone
  hasPassword
  hasMfaOn
  externalAuthProviderNames
  householdRole
  createdAt
  avatarColor
  pendingEmailUpdateVerification {
    email
    __typename
  }
  profilePicture {
    id
    cloudinaryPublicId
    thumbnailUrl
    __typename
  }
  profilePictureUrl
  activeSupportAccountAccessGrant {
    id
    createdAt
    expiresAt
    __typename
  }
  __typename
}
